import type{WorkspaceFile,WorkspaceFileType}from'../types/editor';

export function fileTypeFromName(name:string):WorkspaceFileType|null{const lower=name.toLowerCase();if(lower.endsWith('.html')||lower.endsWith('.htm'))return'html';if(lower.endsWith('.css'))return'css';if(lower.endsWith('.js'))return'js';return null}
export function makeWorkspaceFile(name:string,type:WorkspaceFileType,content=''):WorkspaceFile{return{id:crypto.randomUUID(),name,type,content,updatedAt:Date.now()}}
export function defaultContent(type:WorkspaceFileType){if(type==='html')return'<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>New Page</title>\n</head>\n<body>\n  <h1>Hello world</h1>\n</body>\n</html>\n';if(type==='css')return'/* Styles */\n';return'// JavaScript\n'}
function normalizePath(value:string){return value.split('?')[0].split('#')[0].replace(/^\.\//,'')}
function escapeStyle(css:string){return css.replace(/<\/style/gi,'<\\/style')}
function escapeScript(js:string){return js.replace(/<\/script/gi,'<\\/script')}
export function renderWorkspaceHtml(files:WorkspaceFile[],entryFileId:string){const entry=files.find(f=>f.id===entryFileId&&f.type==='html');if(!entry)return'';const byName=new Map(files.map(f=>[f.name,f]));try{const parser=new DOMParser();const doc=parser.parseFromString(entry.content,'text/html');doc.querySelectorAll<HTMLLinkElement>('link[rel~="stylesheet"][href]').forEach(link=>{const f=byName.get(normalizePath(link.getAttribute('href')||''));if(!f||f.type!=='css')return;const style=doc.createElement('style');style.dataset.vpbWorkspaceFile=f.name;style.textContent=escapeStyle(f.content);link.replaceWith(style)});doc.querySelectorAll<HTMLScriptElement>('script[src]').forEach(script=>{const f=byName.get(normalizePath(script.getAttribute('src')||''));if(!f||f.type!=='js')return;const next=doc.createElement('script');for(const a of[...script.attributes])if(a.name!=='src')next.setAttribute(a.name,a.value);next.dataset.vpbWorkspaceFile=f.name;next.textContent=escapeScript(f.content);script.replaceWith(next)});const dt=entry.content.match(/<!doctype[^>]*>/i)?.[0]||'<!DOCTYPE html>';return`${dt}\n${doc.documentElement.outerHTML}`}catch{return entry.content}}
export function downloadFile(file:WorkspaceFile){const mime=file.type==='html'?'text/html':file.type==='css'?'text/css':'text/javascript';const url=URL.createObjectURL(new Blob([file.content],{type:`${mime};charset=utf-8`}));const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
