import type{WorkspaceFile,WorkspaceFileType}from'../types/editor';

export function fileTypeFromName(name:string):WorkspaceFileType|null{const lower=name.toLowerCase();if(lower.endsWith('.html')||lower.endsWith('.htm'))return'html';if(lower.endsWith('.css'))return'css';if(lower.endsWith('.js'))return'js';return null}
export function makeWorkspaceFile(name:string,type:WorkspaceFileType,content=''):WorkspaceFile{return{id:crypto.randomUUID(),name,type,content,updatedAt:Date.now()}}
export function defaultContent(type:WorkspaceFileType){if(type==='html')return'<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>New Page</title>\n</head>\n<body>\n  <h1>Hello world</h1>\n</body>\n</html>\n';if(type==='css')return'/* Styles */\n';return'// JavaScript\n'}
function normalizePath(value:string){return value.split('?')[0].split('#')[0].replace(/^\.\//,'')}
function blockUnsafeInlineCode(doc:Document){doc.querySelectorAll<HTMLScriptElement>('script:not([src])').forEach(script=>{script.dataset.vpbInlineScript='';script.dataset.vpbOriginalType=script.getAttribute('type')||'';script.setAttribute('type','application/x-vpb-blocked')});doc.querySelectorAll<HTMLElement>('*').forEach(el=>{for(const a of[...el.attributes])if(/^on/i.test(a.name)){el.setAttribute(`data-vpb-event-${a.name.toLowerCase()}`,a.value);el.removeAttribute(a.name)}})}
function restoreBlockedCode(root:HTMLElement){root.querySelectorAll<HTMLScriptElement>('script[data-vpb-inline-script]').forEach(script=>{const original=script.dataset.vpbOriginalType||'';if(original)script.setAttribute('type',original);else script.removeAttribute('type');script.removeAttribute('data-vpb-inline-script');script.removeAttribute('data-vpb-original-type')});[root,...root.querySelectorAll<HTMLElement>('*')].forEach(el=>{for(const a of[...el.attributes])if(a.name.startsWith('data-vpb-event-')){el.setAttribute(a.name.slice('data-vpb-event-'.length),a.value);el.removeAttribute(a.name)}})}
export function renderWorkspaceHtml(files:WorkspaceFile[],entryFileId:string){const entry=files.find(f=>f.id===entryFileId&&f.type==='html');if(!entry)return'';const byName=new Map(files.map(f=>[f.name,f]));try{const parser=new DOMParser();const doc=parser.parseFromString(entry.content,'text/html');blockUnsafeInlineCode(doc);doc.querySelectorAll<HTMLLinkElement>('link[rel~="stylesheet"][href]').forEach(link=>{const f=byName.get(normalizePath(link.getAttribute('href')||''));if(!f||f.type!=='css')return;const style=doc.createElement('style');style.dataset.vpbWorkspaceFile=f.name;style.textContent=f.content;link.replaceWith(style)});doc.querySelectorAll<HTMLScriptElement>('script[src]').forEach(script=>{const f=byName.get(normalizePath(script.getAttribute('src')||''));if(!f||f.type!=='js'){script.dataset.vpbExternalScript='';script.dataset.vpbOriginalSrc=script.getAttribute('src')||'';script.dataset.vpbOriginalType=script.getAttribute('type')||'';script.removeAttribute('src');script.setAttribute('type','application/x-vpb-blocked');return}const next=doc.createElement('script');for(const a of[...script.attributes])if(a.name!=='src')next.setAttribute(a.name,a.value);next.dataset.vpbWorkspaceFile=f.name;next.textContent=f.content;script.replaceWith(next)});const dt=entry.content.match(/<!doctype[^>]*>/i)?.[0]||'<!DOCTYPE html>';return`${dt}\n${doc.documentElement.outerHTML}`}catch{return entry.content}}
export function serializeWorkspaceDocument(doc:Document){const clone=doc.documentElement.cloneNode(true)as HTMLElement;clone.querySelectorAll('style[data-vpb-ui]').forEach(el=>el.remove());clone.querySelectorAll<HTMLScriptElement>('script[data-vpb-external-script]').forEach(script=>{const src=script.dataset.vpbOriginalSrc||'';const type=script.dataset.vpbOriginalType||'';if(src)script.setAttribute('src',src);if(type)script.setAttribute('type',type);else script.removeAttribute('type');script.removeAttribute('data-vpb-external-script');script.removeAttribute('data-vpb-original-src');script.removeAttribute('data-vpb-original-type')});restoreBlockedCode(clone);clone.querySelectorAll<HTMLElement>('[data-vpb-workspace-file]').forEach(el=>{const name=el.dataset.vpbWorkspaceFile;if(!name)return;if(el.tagName==='STYLE'){const link=clone.ownerDocument.createElement('link');link.setAttribute('rel','stylesheet');link.setAttribute('href',name);el.replaceWith(link)}else if(el.tagName==='SCRIPT'){const script=clone.ownerDocument.createElement('script');for(const a of[...el.attributes])if(a.name!=='data-vpb-workspace-file')script.setAttribute(a.name,a.value);script.setAttribute('src',name);script.textContent='';el.replaceWith(script)}});[clone,...clone.querySelectorAll<HTMLElement>('*')].forEach(el=>{if(el.hasAttribute('data-vpb-added-draggable'))el.removeAttribute('draggable');[...el.attributes].forEach(a=>{if(a.name.startsWith('data-vpb-'))el.removeAttribute(a.name)})});const dt=doc.doctype?`<!DOCTYPE ${doc.doctype.name}${doc.doctype.publicId?` PUBLIC "${doc.doctype.publicId}"`:''}${doc.doctype.systemId?` "${doc.doctype.systemId}"`:''}>`:'<!DOCTYPE html>';return`${dt}\n${clone.outerHTML}`}
export function downloadFile(file:WorkspaceFile){const mime=file.type==='html'?'text/html':file.type==='css'?'text/css':'text/javascript';const url=URL.createObjectURL(new Blob([file.content],{type:`${mime};charset=utf-8`}));const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
