import{expect,test,type Page}from'@playwright/test';

const html='<!DOCTYPE html><html><body><section id="hero">Hero</section><section class="card">Card</section></body></html>';

async function open(page:Page){await page.goto('./');await page.evaluate(()=>localStorage.clear());await page.locator('input[type="file"]').setInputFiles({name:'rules.html',mimeType:'text/html',buffer:Buffer.from(html)});const frame=page.frameLocator('iframe[title="HTML canvas"]');await frame.locator('#hero').click();const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'CSS'}).click();await props.getByRole('button',{name:'Page CSS'}).click();return{frame,props}}

test('rule manager edits filters renames reorders duplicates and deletes page CSS rules',async({page})=>{const{frame,props}=await open(page);const css=props.getByLabel('Page CSS');await css.fill('#hero { padding: 10px; }\n.card { margin: 4px; }');await css.blur();const manager=props.getByLabel('CSS rule manager');await expect(manager.getByText('#hero',{exact:true})).toBeVisible();await manager.getByLabel('Search CSS rules').fill('card');await expect(manager.getByText('.card',{exact:true})).toBeVisible();await expect(manager.getByText('#hero',{exact:true})).toHaveCount(0);await manager.getByTitle('Clear rule search').click();await manager.getByText('#hero',{exact:true}).click();await manager.getByLabel('CSS rule selector').fill('#hero-main');await manager.getByLabel('CSS rule selector').press('Enter');await expect(css).toHaveValue(/#hero-main/);await manager.getByText('#hero-main',{exact:true}).click();const declarations=manager.getByLabel('Rule declarations');await declarations.fill('padding: 27px; background: rgb(1, 2, 3);');await declarations.blur();await expect(manager.getByLabel('CSS property 1',{exact:true})).toHaveValue('padding');await expect(manager.getByLabel('CSS value 1',{exact:true})).toHaveValue('27px');await manager.getByLabel('CSS value 1',{exact:true}).fill('31px');await manager.getByLabel('CSS value 1',{exact:true}).blur();await expect(css).toHaveValue(/padding: 31px/);await manager.getByTitle('Duplicate CSS rule').click();await expect(manager.getByText('#hero-main',{exact:true})).toHaveCount(2);await manager.getByText('#hero-main',{exact:true}).last().click();await manager.getByTitle('Move CSS rule up').click();await expect(css).toHaveValue(/#hero-main[\s\S]*#hero-main/);await manager.getByText('#hero-main',{exact:true}).first().click();await manager.getByTitle('Delete CSS rule').click();await expect(manager.getByText('#hero-main',{exact:true})).toHaveCount(1);await page.keyboard.press('Control+z');await expect(manager.getByText('#hero-main',{exact:true})).toHaveCount(2);await expect(frame.locator('#hero')).toBeVisible()});

test('rule manager creates rules and structured declarations',async({page})=>{const{props}=await open(page);const manager=props.getByLabel('CSS rule manager');await manager.getByLabel('New CSS selector').fill('.fresh');await manager.getByRole('button',{name:'Add'}).click();await expect(manager.getByText('.fresh',{exact:true})).toBeVisible();await manager.getByText('.fresh',{exact:true}).click();await manager.getByRole('button',{name:'Add declaration'}).click();await manager.getByLabel('CSS property 1',{exact:true}).fill('margin');await manager.getByLabel('CSS value 1',{exact:true}).fill('12px');await manager.getByLabel('CSS value 1',{exact:true}).blur();await expect(props.getByLabel('Page CSS')).toHaveValue(/\.fresh\s*\{[^}]*margin: 12px/)});

test('rule manager creates responsive rule in active device context',async({page})=>{const{props}=await open(page);await page.getByTitle('mobile').click();await props.getByRole('button',{name:'Responsive'}).click();const manager=props.getByLabel('CSS rule manager');await expect(manager.getByLabel('New CSS selector')).toHaveValue('#hero');await manager.getByRole('button',{name:'Add'}).click();await expect(props.getByLabel('Responsive CSS')).toHaveValue(/@media \(max-width: 480px\)[\s\S]*#hero/);await expect(manager.getByText('@media (max-width: 480px)',{exact:true})).toBeVisible()});
