import{expect,test}from'@playwright/test';

const html='<!DOCTYPE html><html><body><section id="hero">Hero</section><section class="card">Card</section></body></html>';

async function open(page){await page.goto('./');await page.evaluate(()=>localStorage.clear());await page.locator('input[type="file"]').setInputFiles({name:'rules.html',mimeType:'text/html',buffer:Buffer.from(html)});const frame=page.frameLocator('iframe[title="HTML canvas"]');await frame.locator('#hero').click();const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'CSS'}).click();await props.getByRole('button',{name:'Page CSS'}).click();return{frame,props}}

test('rule manager edits duplicates and deletes page CSS rules',async({page})=>{const{frame,props}=await open(page);const css=props.getByLabel('Page CSS');await css.fill('#hero { padding: 10px; }\n.card { margin: 4px; }');await css.blur();const manager=props.getByLabel('CSS rule manager');await expect(manager.getByText('#hero',{exact:true})).toBeVisible();await manager.getByText('#hero',{exact:true}).click();const declarations=manager.getByLabel('Rule declarations');await declarations.fill('padding: 27px; background: rgb(1, 2, 3);');await expect(frame.locator('#hero')).toHaveCSS('padding-top','27px');await declarations.blur();await manager.getByTitle('Duplicate CSS rule').click();await expect(manager.getByText('#hero',{exact:true})).toHaveCount(2);await manager.getByText('#hero',{exact:true}).first().click();await manager.getByTitle('Delete CSS rule').click();await expect(manager.getByText('#hero',{exact:true})).toHaveCount(1);await page.keyboard.press('Control+z');await expect(manager.getByText('#hero',{exact:true})).toHaveCount(2)});

test('rule manager exposes nested responsive rules with media context',async({page})=>{const{props}=await open(page);await props.getByRole('button',{name:'Responsive'}).click();const css=props.getByLabel('Responsive CSS');await css.fill('@media (max-width: 480px) { #hero { padding: 18px; } }');await css.blur();const manager=props.getByLabel('CSS rule manager');await expect(manager.getByText('#hero',{exact:true})).toBeVisible();await expect(manager.getByText('@media (max-width: 480px)',{exact:true})).toBeVisible()});
