import{expect,test,type Page}from'@playwright/test';

const html='<!DOCTYPE html><html><head><title>Props</title></head><body><main><section id="hero" class="old"><h2>Hero heading</h2></section><section id="taken">Taken</section></main></body></html>';

async function open(page:Page){await page.goto('./');await page.evaluate(()=>localStorage.clear());await page.locator('input[type="file"]').setInputFiles({name:'props.html',mimeType:'text/html',buffer:Buffer.from(html)});const frame=page.frameLocator('iframe[title="HTML canvas"]');await expect(frame.locator('#hero')).toBeVisible();await frame.locator('#hero').click({position:{x:4,y:4}});return frame}

test('selected block edits id class title and custom attributes',async({page})=>{const frame=await open(page);const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'Attributes'}).click();const id=props.getByLabel('Element ID');await id.fill('hero-new');await id.blur();await expect(frame.locator('#hero-new')).toBeVisible();const cls=props.getByLabel('Element class');await cls.fill('hero dark');await cls.blur();await expect(frame.locator('#hero-new')).toHaveClass('hero dark');const title=props.getByLabel('Element title');await title.fill('Main hero');await title.blur();await expect(frame.locator('#hero-new')).toHaveAttribute('title','Main hero');await props.getByLabel('New attribute name').fill('data-section');await props.getByLabel('New attribute value').fill('landing');await props.getByRole('button',{name:/Add attribute/i}).click();await expect(frame.locator('#hero-new')).toHaveAttribute('data-section','landing')});

test('duplicate id is rejected',async({page})=>{const frame=await open(page);const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'Attributes'}).click();const id=props.getByLabel('Element ID');await id.fill('taken');await id.blur();await expect(props.getByText('ID already exists')).toBeVisible();await expect(frame.locator('#hero')).toBeVisible();await expect(frame.locator('#taken')).toHaveCount(1)});

test('inline and page CSS apply and export cleanly',async({page})=>{const frame=await open(page);const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'CSS'}).click();const inline=props.getByLabel('Element CSS');await inline.fill('padding: 31px; background-color: rgb(7, 8, 9);');await props.getByRole('button',{name:'Apply CSS'}).click();await expect(frame.locator('#hero')).toHaveCSS('padding-top','31px');await props.getByRole('button',{name:'Page CSS'}).click();const pageCss=props.getByLabel('Page CSS');await pageCss.fill('#hero { color: rgb(1, 2, 3); }');await props.getByRole('button',{name:'Apply CSS'}).click();await expect(frame.locator('#hero')).toHaveCSS('color','rgb(1, 2, 3)');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:/Export HTML/i}).click();const download=await downloadPromise;const stream=await download.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));const exported=Buffer.concat(chunks).toString('utf8');expect(exported).toContain('padding: 31px');expect(exported).toContain('#hero { color: rgb(1, 2, 3); }');expect(exported).not.toContain('data-vpb-user-css');expect(exported).not.toContain('data-vpb-id')});

test('live CSS typing is grouped into one undo step and autosaved',async({page})=>{const frame=await open(page);const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'CSS'}).click();const inline=props.getByLabel('Element CSS');await inline.fill('padding: 11px;');await expect(frame.locator('#hero')).toHaveCSS('padding-top','11px');await inline.fill('padding: 22px;');await expect(frame.locator('#hero')).toHaveCSS('padding-top','22px');await inline.fill('padding: 33px;');await expect(frame.locator('#hero')).toHaveCSS('padding-top','33px');await inline.blur();await page.waitForTimeout(500);const saved=await page.evaluate(()=>localStorage.getItem('visual-html-page-builder:draft:v1'));expect(saved).toContain('padding: 33px');await page.keyboard.press('Control+z');await expect(frame.locator('#hero')).toHaveCSS('padding-top','0px');await page.waitForTimeout(500);const reverted=await page.evaluate(()=>localStorage.getItem('visual-html-page-builder:draft:v1'));expect(reverted).not.toContain('padding: 33px')});

test('responsive CSS inserts a rule for active mobile preview and persists in export',async({page})=>{const frame=await open(page);await page.getByTitle('mobile').click();const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'CSS'}).click();await props.getByRole('button',{name:'Responsive'}).click();await expect(props.getByText('mobile',{exact:true})).toBeVisible();await props.getByRole('button',{name:/Insert rule/i}).click();const css=props.getByLabel('Responsive CSS');await expect(css).toHaveValue(/@media \(max-width: 480px\)/);await css.fill('@media (max-width: 480px) {\n  #hero { padding: 24px; }\n}');await expect(frame.locator('#hero')).toHaveCSS('padding-top','24px');await css.blur();await page.waitForTimeout(450);const saved=await page.evaluate(()=>localStorage.getItem('visual-html-page-builder:draft:v1'));expect(saved).toContain('max-width: 480px');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:/Export HTML/i}).click();const download=await downloadPromise;const stream=await download.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream)chunks.push(Buffer.from(chunk));const exported=Buffer.concat(chunks).toString('utf8');expect(exported).toContain('@media (max-width: 480px)');expect(exported).toContain('#hero { padding: 24px; }');expect(exported).not.toContain('data-vpb-responsive-css')});
