import{expect,test}from'@playwright/test';

const html='<!DOCTYPE html><html><body><main><section id="outer"><div id="inner">Inner</div></section><section id="empty"></section><form><input id="field" value="abc"></form></main></body></html>';

async function open(page){await page.goto('./');await page.evaluate(()=>localStorage.clear());await page.locator('input[type="file"]').setInputFiles({name:'selection.html',mimeType:'text/html',buffer:Buffer.from(html)});const frame=page.frameLocator('iframe[title="HTML canvas"]');await expect(frame.locator('#inner')).toBeVisible();return frame}

test('tree selection synchronizes canvas outline toolbar and breadcrumbs',async({page})=>{const frame=await open(page);const elements=page.locator('aside').filter({hasText:'Elements'}).first();await elements.getByRole('tab',{name:'tree'}).click();await elements.getByRole('button',{name:/div inner/i}).click();await expect(frame.locator('#inner')).toHaveAttribute('data-vpb-selected','');await expect(page.getByTestId('canvas-block-toolbar')).toBeVisible();const props=page.locator('aside').filter({hasText:'Properties'}).last();const crumbs=props.getByLabel('Element breadcrumbs');await expect(crumbs).toContainText('<body>');await expect(crumbs).toContainText('<main>');await expect(crumbs).toContainText('<section>');await expect(crumbs).toContainText('<div>');await crumbs.getByRole('button',{name:'<section>'}).click();await expect(frame.locator('#outer')).toHaveAttribute('data-vpb-selected','')});

test('empty layout blocks keep an editor-only selectable footprint',async({page})=>{const frame=await open(page);await expect(frame.locator('#empty')).toHaveCSS('min-height','32px');await frame.locator('#empty').click({position:{x:4,y:4}});await expect(page.getByTestId('canvas-block-toolbar')).toBeVisible()});

test('canvas block shortcuts duplicate move copy paste and delete without hijacking inputs',async({page})=>{const frame=await open(page);await frame.locator('#inner').click();await frame.locator('#inner').press('Control+d');await expect(frame.locator('#outer > div')).toHaveCount(2);await frame.locator('#outer > div').last().press('Control+Shift+c');await frame.locator('#outer > div').last().press('Control+Shift+v');await expect(frame.locator('#outer > div')).toHaveCount(3);await frame.locator('#empty').click();await frame.locator('#empty').press('Delete');await expect(frame.locator('#empty')).toHaveCount(0);await frame.locator('#field').click();await frame.locator('#field').press('Delete');await expect(frame.locator('#field')).toHaveCount(1)});
