import{expect,test}from'@playwright/test';

const html='<!DOCTYPE html><html><body><main><section id="source" style="padding: 28px; background-color: rgb(10, 20, 30);">Source</section><section id="target" class="keep-me">Target</section></main></body></html>';

async function open(page:any){await page.goto('./');await page.evaluate(()=>localStorage.clear());await page.locator('input[type="file"]').setInputFiles({name:'styles.html',mimeType:'text/html',buffer:Buffer.from(html)});const frame=page.frameLocator('iframe[title="HTML canvas"]');await expect(frame.locator('#source')).toBeVisible();return frame}

test('copies and pastes only inline style between selected blocks',async({page})=>{const frame=await open(page);await frame.locator('#source').click();const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'CSS'}).click();await props.getByRole('button',{name:'Copy Style'}).click();await frame.locator('#target').click();await props.getByRole('tab',{name:'CSS'}).click();await expect(props.getByRole('button',{name:'Paste Style'})).toBeEnabled();await props.getByRole('button',{name:'Paste Style'}).click();await expect(frame.locator('#target')).toHaveCSS('padding-top','28px');await expect(frame.locator('#target')).toHaveCSS('background-color','rgb(10, 20, 30)');await expect(frame.locator('#target')).toHaveClass('keep-me');await expect(frame.locator('#target')).toHaveText('Target');await page.keyboard.press('Control+z');await expect(frame.locator('#target')).toHaveCSS('padding-top','0px')});

test('clear inline style is undoable and autosaved',async({page})=>{const frame=await open(page);await frame.locator('#source').click();const props=page.locator('aside').filter({hasText:'Properties'}).last();await props.getByRole('tab',{name:'CSS'}).click();await props.getByRole('button',{name:'Clear Style'}).click();await expect(frame.locator('#source')).not.toHaveAttribute('style');await page.waitForTimeout(450);const saved=await page.evaluate(()=>localStorage.getItem('visual-html-page-builder:draft:v1'));expect(saved).not.toContain('padding: 28px');await page.keyboard.press('Control+z');await expect(frame.locator('#source')).toHaveCSS('padding-top','28px')});
