import{expect,test}from'@playwright/test';

const key='visual-html-page-builder:draft:v2';
const workspace={version:2,files:[
  {id:'html-1',name:'index.html',type:'html',content:'<!DOCTYPE html><html><head><link rel="stylesheet" href="style.css"></head><body><div id="target">Workspace</div><button id="unsafe" onclick="window.__inlineRan=true">unsafe</button><script>window.__inlineScriptRan=true</script><script src="app.js"></script></body></html>',updatedAt:1},
  {id:'css-1',name:'style.css',type:'css',content:'#target { color: rgb(12, 34, 56); padding: 17px; }',updatedAt:1},
  {id:'js-1',name:'app.js',type:'js',content:'document.getElementById("target")?.setAttribute("data-workspace-js","ok"); window.__workspaceRan=true;',updatedAt:1}
],activeFileId:'html-1',entryFileId:'html-1',device:'desktop',savedAt:1};

async function openWorkspace(page:any){await page.goto('./');await page.evaluate(({key,workspace})=>{localStorage.clear();localStorage.setItem(key,JSON.stringify(workspace))},{key,workspace});await page.reload();return page.frameLocator('iframe[title="HTML canvas"]')}

test('workspace resolves local CSS and JS while uploaded inline code stays blocked',async({page})=>{const frame=await openWorkspace(page);const target=frame.locator('#target');await expect(target).toHaveCSS('color','rgb(12, 34, 56)');await expect(target).toHaveCSS('padding-top','17px');await expect(target).toHaveAttribute('data-workspace-js','ok');expect(await target.evaluate(()=>Boolean((window as any).__workspaceRan))).toBe(true);expect(await target.evaluate(()=>typeof (window as any).__inlineScriptRan)).toBe('undefined');await frame.locator('#unsafe').click();expect(await target.evaluate(()=>typeof (window as any).__inlineRan)).toBe('undefined')});

test('raw mode exposes workspace files and persists active file selection',async({page})=>{await openWorkspace(page);await page.getByTestId('mode-raw').click();await expect(page.getByTestId('raw-editor')).toBeVisible();for(const name of['index.html','style.css','app.js'])await expect(page.getByTestId('raw-editor').getByRole('button',{name:new RegExp(name.replace('.','\\.'))})).toBeVisible();await page.getByTestId('raw-editor').getByRole('button',{name:'style.css'}).click();await expect(page.locator('.monaco-editor')).toBeVisible();await page.waitForTimeout(500);const active=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)||'{}').activeFileId,key);expect(active).toBe('css-1')});

test('file explorer creates html css and js files and opens them in raw mode',async({page})=>{await page.goto('./');await page.evaluate(()=>localStorage.clear());await page.reload();await page.getByRole('button',{name:'Files',exact:true}).click();page.once('dialog',d=>d.accept('theme'));await page.getByTitle('New CSS').click();await expect(page.getByTestId('mode-raw')).toHaveClass(/bg-zinc-700/);await expect(page.getByTestId('raw-editor').getByRole('button',{name:'theme.css'})).toBeVisible();page.once('dialog',d=>d.accept('main'));await page.getByTitle('New JavaScript').click();await expect(page.getByTestId('raw-editor').getByRole('button',{name:'main.js'})).toBeVisible();page.once('dialog',d=>d.accept('about'));await page.getByTitle('New HTML').click();await expect(page.getByTestId('raw-editor').getByRole('button',{name:'about.html'})).toBeVisible();await page.waitForTimeout(500);const names=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)||'{}').files?.map((f:any)=>f.name)||[],key);expect(names).toEqual(expect.arrayContaining(['index.html','theme.css','main.js','about.html']))});
