import{useEffect,useState}from'react';
import{Check,Code2,Plus,Smartphone,Tablet,Monitor,Target,ClipboardCopy,ClipboardPaste,Eraser}from'lucide-react';
import{createUniqueElementId}from'../editor/attributes';
import{CssRuleManager}from'../components/CssRuleManager';
import type{EditorContextValue}from'../types/editor';

function selectedElement(e:EditorContextValue){const d=e.iframeRef.current?.contentDocument;return d&&e.selectedId?d.querySelector<HTMLElement>(`[data-vpb-id="${CSS.escape(e.selectedId)}"]`):null}
function pageStyle(doc:Document){return doc.querySelector<HTMLStyleElement>('style[data-vpb-user-css]')||[...doc.querySelectorAll<HTMLStyleElement>('style')].find(x=>x.textContent?.includes('/* vpb-user-css */'))||null}
function responsiveStyle(doc:Document){return doc.querySelector<HTMLStyleElement>('style[data-vpb-responsive-css]')||[...doc.querySelectorAll<HTMLStyleElement>('style')].find(x=>x.textContent?.includes('/* vpb-responsive-css */'))||null}
function autoSelector(el:HTMLElement|null){if(!el)return'';if(el.id)return`#${CSS.escape(el.id)}`;const cls=[...el.classList][0];if(cls)return`.${CSS.escape(cls)}`;return el.tagName.toLowerCase()}

type CssTab='inline'|'page'|'responsive';
type CssState='normal'|'hover'|'focus'|'active';
type SelectorTarget='auto'|'id'|'class'|'tag';
const states:{id:CssState;label:string;suffix:string}[]=[{id:'normal',label:'Normal',suffix:''},{id:'hover',label:'Hover',suffix:':hover'},{id:'focus',label:'Focus',suffix:':focus'},{id:'active',label:'Active',suffix:':active'}];
const targets:{id:SelectorTarget;label:string}[]=[{id:'auto',label:'Auto'},{id:'id',label:'ID'},{id:'class',label:'Class'},{id:'tag',label:'Tag'}];

export function CssPanel({e}:{e:EditorContextValue}){
  const[tab,setTabState]=useState<CssTab>('inline');const[state,setState]=useState<CssState>('normal');const[target,setTarget]=useState<SelectorTarget>('auto');const[selectedClass,setSelectedClass]=useState('');const[current,setCurrent]=useState('');const[pageCss,setPageCss]=useState('');const[responsiveCss,setResponsiveCss]=useState('');const[applied,setApplied]=useState(false);
  const selected=selectedElement(e);
  const classes=selected?[...selected.classList]:[];
  const baseSelector=selected?(target==='auto'?autoSelector(selected):target==='id'?(selected.id?`#${CSS.escape(selected.id)}`:''):target==='class'?(selectedClass?`.${CSS.escape(selectedClass)}`:''):selected.tagName.toLowerCase()):'';
  const stateSuffix=states.find(x=>x.id===state)?.suffix||'';
  const effectiveSelector=baseSelector?`${baseSelector}${stateSuffix}`:'';
  const autoIsScoped=!!selected?.id;

  useEffect(()=>{const el=selectedElement(e);setCurrent(el?.style.cssText||'');const d=e.iframeRef.current?.contentDocument;setPageCss(d?pageStyle(d)?.textContent?.replace('/* vpb-user-css */','').trimStart()||'':'');setResponsiveCss(d?responsiveStyle(d)?.textContent?.replace('/* vpb-responsive-css */','').trimStart()||'':'');setApplied(false)},[e.selectedId,e.analysis]);
  useEffect(()=>{const el=selectedElement(e);setTarget('auto');setState('normal');setSelectedClass(el?.classList[0]||'')},[e.selectedId]);
  useEffect(()=>{if(selectedClass&&!classes.includes(selectedClass))setSelectedClass(classes[0]||'');else if(!selectedClass&&classes.length)setSelectedClass(classes[0])},[e.analysis]);

  const flash=()=>{setApplied(true);window.setTimeout(()=>setApplied(false),1200)};
  const setTab=(next:CssTab)=>{e.flushGroupedMutation();setTabState(next)};
  const changeState=(next:CssState)=>{e.flushGroupedMutation();setState(next)};
  const changeTarget=(next:SelectorTarget)=>{e.flushGroupedMutation();setTarget(next)};
  const changeInline=(value:string)=>{setCurrent(value);setApplied(false);e.mutateGrouped(`css:inline:${e.selectedId}`,el=>{el.style.cssText=value})};
  const changePage=(value:string)=>{setPageCss(value);setApplied(false);const d=e.iframeRef.current?.contentDocument;if(!d)return;e.mutateGrouped('css:page',()=>{let style=pageStyle(d);if(!style){style=d.createElement('style');style.dataset.vpbUserCss='';d.head?.append(style)}style.textContent=`/* vpb-user-css */\n${value}`})};
  const changeResponsive=(value:string)=>{setResponsiveCss(value);setApplied(false);const d=e.iframeRef.current?.contentDocument;if(!d)return;e.mutateGrouped('css:responsive',()=>{let style=responsiveStyle(d);if(!style){style=d.createElement('style');style.dataset.vpbResponsiveCss='';d.head?.append(style)}style.textContent=`/* vpb-responsive-css */\n${value}`})};
  const apply=()=>{e.flushGroupedMutation();flash()};
  const createScopedId=()=>{const el=selectedElement(e);const d=el?.ownerDocument;if(!el||!d||el.id)return;e.mutate(node=>{node.id=createUniqueElementId(d,node)});setTarget('id')};
  const insertSelector=()=>{if(!effectiveSelector)return;const next=`${pageCss}${pageCss.trim()?`\n\n`:''}${effectiveSelector} {\n  \n}`;setTabState('page');changePage(next)};
  const insertResponsiveRule=()=>{if(!effectiveSelector)return;let block='';if(e.device==='desktop')block=`${effectiveSelector} {\n  \n}`;else if(e.device==='tablet')block=`@media (max-width: 768px) {\n  ${effectiveSelector} {\n    \n  }\n}`;else block=`@media (max-width: 480px) {\n  ${effectiveSelector} {\n    \n  }\n}`;const next=`${responsiveCss}${responsiveCss.trim()?`\n\n`:''}${block}`;setTabState('responsive');changeResponsive(next)};
  const active=tab==='inline'?current:tab==='page'?pageCss:responsiveCss;
  const change=tab==='inline'?changeInline:tab==='page'?changePage:changeResponsive;
  const DeviceIcon=e.device==='desktop'?Monitor:e.device==='tablet'?Tablet:Smartphone;
  return <div className="p-3">
    <div className="grid grid-cols-3 rounded-md border border-zinc-800 bg-zinc-900 p-0.5"><button onClick={()=>setTab('inline')} className={`rounded px-1 py-2 text-[11px] font-medium ${tab==='inline'?'bg-zinc-700 text-white':'text-zinc-500 hover:text-zinc-200'}`}>Inline</button><button onClick={()=>setTab('page')} className={`rounded px-1 py-2 text-[11px] font-medium ${tab==='page'?'bg-zinc-700 text-white':'text-zinc-500 hover:text-zinc-200'}`}>Page CSS</button><button onClick={()=>setTab('responsive')} className={`rounded px-1 py-2 text-[11px] font-medium ${tab==='responsive'?'bg-zinc-700 text-white':'text-zinc-500 hover:text-zinc-200'}`}>Responsive</button></div>
    <div className="mt-3 mb-2 flex items-center justify-between gap-2 text-[11px] text-zinc-500"><span className="inline-flex items-center gap-1"><Code2 size={12}/>{tab==='inline'?'Style attribute for selected element':tab==='page'?'CSS rules stored in this document':'Device-aware CSS rules'}</span>{applied&&<span className="inline-flex items-center gap-1 text-emerald-400"><Check size={12}/>Saved</span>}</div>
    {tab==='inline'&&<div className="mb-2 grid grid-cols-3 gap-1 rounded-md border border-zinc-800 bg-zinc-900/50 p-1.5" aria-label="Inline style actions"><button onClick={e.copyStyle} className="inline-flex items-center justify-center gap-1 rounded px-2 py-1.5 text-[10px] text-zinc-300 hover:bg-zinc-800"><ClipboardCopy size={12}/>Copy Style</button><button onClick={e.pasteStyle} disabled={!e.hasCopiedStyle} className="inline-flex items-center justify-center gap-1 rounded px-2 py-1.5 text-[10px] text-zinc-300 hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-35"><ClipboardPaste size={12}/>Paste Style</button><button onClick={e.clearInlineStyle} disabled={!current.trim()} className="inline-flex items-center justify-center gap-1 rounded px-2 py-1.5 text-[10px] text-zinc-300 hover:bg-red-500/10 hover:text-red-300 disabled:cursor-not-allowed disabled:opacity-35"><Eraser size={12}/>Clear Style</button></div>}
    {tab!=='inline'&&<><div className="mb-2"><div className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-zinc-600">Selector target</div><div className="grid grid-cols-4 rounded-md border border-zinc-800 bg-zinc-900 p-0.5" aria-label="Selector target">{targets.map(t=><button key={t.id} onClick={()=>changeTarget(t.id)} disabled={(t.id==='id'&&!selected?.id)||(t.id==='class'&&!classes.length)} aria-pressed={target===t.id} className={`rounded px-1 py-1.5 text-[10px] font-medium ${target===t.id?'bg-violet-500/15 text-violet-300':'text-zinc-500 hover:text-zinc-200'} disabled:cursor-not-allowed disabled:opacity-30`}>{t.label}</button>)}</div>{target==='class'&&classes.length>1&&<select aria-label="CSS selector class" value={selectedClass} onChange={x=>setSelectedClass(x.target.value)} className="mt-1.5 w-full rounded-md border border-zinc-800 bg-zinc-950 px-2 py-1.5 text-[11px] text-zinc-300 outline-none focus:border-blue-500">{classes.map(c=><option key={c} value={c}>.{c}</option>)}</select>}</div><div className="mb-2"><div className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-zinc-600">State</div><div className="grid grid-cols-4 rounded-md border border-zinc-800 bg-zinc-900 p-0.5" aria-label="CSS state">{states.map(s=><button key={s.id} onClick={()=>changeState(s.id)} aria-pressed={state===s.id} className={`rounded px-1 py-1.5 text-[10px] font-medium ${state===s.id?'bg-blue-500/15 text-blue-300':'text-zinc-500 hover:text-zinc-200'}`}>{s.label}</button>)}</div></div></>}
    {tab!=='inline'&&target==='auto'&&!autoIsScoped&&<div className="mb-2 rounded-md border border-amber-500/20 bg-amber-500/5 p-2"><div className="flex items-start gap-2"><Target size={13} className="mt-0.5 shrink-0 text-amber-400"/><div className="min-w-0 flex-1"><div className="text-[10px] font-medium text-amber-200">Selector is not uniquely scoped</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-500">Current selector <code className="text-zinc-300">{baseSelector||'—'}</code> may match other elements.</div></div><button onClick={createScopedId} className="shrink-0 rounded bg-amber-500/15 px-2 py-1 text-[10px] font-medium text-amber-200 hover:bg-amber-500/25">Create unique ID</button></div></div>}
    {tab==='page'&&<div className="mb-2 flex items-center gap-2 rounded-md border border-zinc-800 bg-zinc-900/50 p-2"><code className="min-w-0 flex-1 truncate text-[11px] text-blue-300">{effectiveSelector||'No selector'}</code><button onClick={insertSelector} disabled={!effectiveSelector} className="inline-flex shrink-0 items-center gap-1 rounded bg-zinc-800 px-2 py-1 text-[10px] text-zinc-300 hover:bg-zinc-700 disabled:opacity-40"><Plus size={11}/>Insert selector</button></div>}
    {tab==='responsive'&&<div className="mb-2 rounded-md border border-zinc-800 bg-zinc-900/50 p-2"><div className="flex items-center gap-2"><span className="inline-flex items-center gap-1 text-[10px] uppercase tracking-wide text-zinc-500"><DeviceIcon size={12}/>{e.device}</span><code className="min-w-0 flex-1 truncate text-[11px] text-blue-300">{effectiveSelector||'No selector'}</code><button onClick={insertResponsiveRule} disabled={!effectiveSelector} className="inline-flex shrink-0 items-center gap-1 rounded bg-zinc-800 px-2 py-1 text-[10px] text-zinc-300 hover:bg-zinc-700 disabled:opacity-40"><Plus size={11}/>Insert rule</button></div><div className="mt-1.5 text-[10px] text-zinc-600">Desktop: global · Tablet: ≤768px · Mobile: ≤480px</div></div>}
    {tab!=='inline'&&<CssRuleManager css={active} onChange={change} onCommit={e.flushGroupedMutation}/>} 
    <textarea aria-label={tab==='inline'?'Element CSS':tab==='page'?'Page CSS':'Responsive CSS'} value={active} onChange={x=>change(x.target.value)} onBlur={e.flushGroupedMutation} onKeyDown={x=>{if((x.ctrlKey||x.metaKey)&&x.key==='Enter'){x.preventDefault();apply()}}} spellCheck={false} placeholder={tab==='inline'?'color: white;\npadding: 20px;\nbackground: #111827;':tab==='page'?'.card:hover {\n  transform: translateY(-2px);\n}':'@media (max-width: 480px) {\n  .card:hover {\n    opacity: .9;\n  }\n}'} className="min-h-52 w-full resize-y rounded-md border border-zinc-700 bg-zinc-950 p-3 font-mono text-xs leading-5 text-zinc-200 outline-none focus:border-blue-500"/>
    <div className="mt-2 flex items-center justify-between gap-2"><span className="text-[10px] text-zinc-600">Live preview · changes group after 350ms</span><button onClick={apply} className="rounded-md bg-blue-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-400">Apply CSS</button></div>
  </div>;
}
