import{useCallback,useEffect,useRef,useState}from'react';
import{ArrowDown,ArrowUp,ClipboardCopy,ClipboardPaste,Copy,Trash2}from'lucide-react';
import{indexDocument,ID}from'../editor/selection';
import{BLOCK_DRAG_TYPE,ELEMENT_DRAG_TYPE}from'../editor/drag';
import type{EditorContextValue,InsertPosition}from'../types/editor';

const widths={desktop:'100%',tablet:'768px',mobile:'375px'};
const voidTags=new Set(['AREA','BASE','BR','COL','EMBED','HR','IMG','INPUT','LINK','META','PARAM','SOURCE','TRACK','WBR','IFRAME']);
type ToolbarPos={left:number;top:number;tag:string}|null;

function dropPosition(target:HTMLElement,clientY:number):InsertPosition{if(voidTags.has(target.tagName))return clientY<target.getBoundingClientRect().top+target.getBoundingClientRect().height/2?'before':'after';const rect=target.getBoundingClientRect();const ratio=rect.height?((clientY-rect.top)/rect.height):.5;if(ratio<.25)return'before';if(ratio>.75)return'after';return'inside'}
function editingTarget(target:EventTarget|null){const el=target as HTMLElement|null;return !!el&&(el.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(el.tagName))}

export function Canvas({e}:{e:EditorContextValue}){
  const[toolbar,setToolbar]=useState<ToolbarPos>(null);
  const editorRef=useRef(e);editorRef.current=e;
  const positionToolbar=useCallback(()=>{const current=editorRef.current;const f=current.iframeRef.current,d=f?.contentDocument;if(!f||!d||!current.selectedId){setToolbar(null);return}const el=d.querySelector<HTMLElement>(`[${ID}="${CSS.escape(current.selectedId)}"]`);if(!el||['HTML','BODY'].includes(el.tagName)){setToolbar(null);return}const rect=el.getBoundingClientRect();const maxLeft=Math.max(8,f.clientWidth-292);setToolbar({left:Math.max(8,Math.min(rect.left,maxLeft)),top:Math.max(8,rect.top-38),tag:el.tagName.toLowerCase()})},[]);
  useEffect(()=>{positionToolbar()},[positionToolbar,e.selectedId,e.device]);

  useEffect(()=>{
    const f=e.iframeRef.current;if(!f)return;let cleanupDocument=()=>{};
    const onLoad=()=>{
      cleanupDocument();const d=f.contentDocument;if(!d)return;indexDocument(d);
      const style=d.createElement('style');style.dataset.vpbUi='';style.textContent='[data-vpb-hover]{outline:2px dashed #60a5fa!important;outline-offset:2px}[data-vpb-selected]{outline:2px solid #2563eb!important;outline-offset:2px}[data-vpb-drop="inside"]{box-shadow:inset 0 0 0 3px #22c55e!important}[data-vpb-drop="before"]{box-shadow:inset 0 3px 0 #22c55e!important}[data-vpb-drop="after"]{box-shadow:inset 0 -3px 0 #22c55e!important}[data-vpb-dragging]{opacity:.45!important}section:empty,div:empty,header:empty,main:empty,nav:empty,article:empty,aside:empty,footer:empty,form:empty,figure:empty{min-height:32px!important;outline:1px dashed #a1a1aa55!important;outline-offset:-2px}section:empty::before,div:empty::before,header:empty::before,main:empty::before,nav:empty::before,article:empty::before,aside:empty::before,footer:empty::before,form:empty::before,figure:empty::before{content:"Empty block";display:block;padding:7px;font:10px/1.5 ui-monospace,monospace;color:#71717a;background:#18181b0d}';d.head?.append(style);
      let hover:HTMLElement|null=null,dropTarget:HTMLElement|null=null,dragSource:HTMLElement|null=null;
      const clearDrop=()=>{dropTarget?.removeAttribute('data-vpb-drop');dropTarget=null};
      const updateToolbar=()=>requestAnimationFrame(positionToolbar);
      const mouseover=(ev:MouseEvent)=>{const t=ev.target as HTMLElement;if(!t?.getAttribute)return;hover?.removeAttribute('data-vpb-hover');hover=t;hover.setAttribute('data-vpb-hover','')};
      const mouseout=()=>{hover?.removeAttribute('data-vpb-hover');hover=null};
      const click=(ev:MouseEvent)=>{ev.preventDefault();ev.stopPropagation();const t=ev.target as HTMLElement;editorRef.current.select(t.getAttribute(ID));updateToolbar()};
      const submit=(ev:Event)=>ev.preventDefault();
      const scroll=()=>updateToolbar();
      const resize=()=>updateToolbar();
      const keydown=(ev:KeyboardEvent)=>{if(editingTarget(ev.target))return;const current=editorRef.current;if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='d'){ev.preventDefault();current.duplicate();return}if((ev.ctrlKey||ev.metaKey)&&ev.shiftKey&&ev.key.toLowerCase()==='c'){ev.preventDefault();current.copyBlock();return}if((ev.ctrlKey||ev.metaKey)&&ev.shiftKey&&ev.key.toLowerCase()==='v'){ev.preventDefault();current.pasteBlock('after');return}if(ev.altKey&&ev.key==='ArrowUp'){ev.preventDefault();current.move(-1);return}if(ev.altKey&&ev.key==='ArrowDown'){ev.preventDefault();current.move(1);return}if(ev.key==='Delete'||ev.key==='Backspace'){ev.preventDefault();current.remove();setToolbar(null)}};
      const dragstart=(ev:DragEvent)=>{const t=ev.target as HTMLElement,sourceId=t?.getAttribute?.(ID);if(!sourceId||['BODY','HTML'].includes(t.tagName)||!ev.dataTransfer)return;dragSource=t;t.setAttribute('data-vpb-dragging','');ev.dataTransfer.effectAllowed='move';ev.dataTransfer.setData(BLOCK_DRAG_TYPE,sourceId);ev.dataTransfer.setData('text/plain',sourceId)};
      const dragover=(ev:DragEvent)=>{const types=[...ev.dataTransfer?.types||[]],isPalette=types.includes(ELEMENT_DRAG_TYPE),isMove=types.includes(BLOCK_DRAG_TYPE);if(!isPalette&&!isMove)return;const t=ev.target as HTMLElement;if(!t?.getAttribute)return;const moveId=isMove?ev.dataTransfer?.getData(BLOCK_DRAG_TYPE):null;const source=moveId?d.querySelector<HTMLElement>(`[${ID}="${CSS.escape(moveId)}"]`):dragSource;if(isMove&&source&&(source===t||source.contains(t))){clearDrop();return}ev.preventDefault();if(ev.dataTransfer)ev.dataTransfer.dropEffect=isMove?'move':'copy';const pos=dropPosition(t,ev.clientY);if(dropTarget!==t){clearDrop();dropTarget=t}dropTarget.setAttribute('data-vpb-drop',pos)};
      const dragleave=(ev:DragEvent)=>{if(!(ev.relatedTarget instanceof d.defaultView!.Node))clearDrop()};
      const drop=(ev:DragEvent)=>{const kind=ev.dataTransfer?.getData(ELEMENT_DRAG_TYPE),sourceId=ev.dataTransfer?.getData(BLOCK_DRAG_TYPE);if(!kind&&!sourceId)return;ev.preventDefault();ev.stopPropagation();const t=ev.target as HTMLElement,targetId=t.getAttribute(ID);if(!targetId){clearDrop();return}const pos=dropPosition(t,ev.clientY);clearDrop();if(sourceId)editorRef.current.moveBlock(sourceId,targetId,pos);else if(kind)editorRef.current.insertElement(kind,pos,targetId);setTimeout(updateToolbar)};
      const dragend=()=>{clearDrop();dragSource?.removeAttribute('data-vpb-dragging');dragSource=null;setTimeout(updateToolbar)};
      d.addEventListener('mouseover',mouseover);d.addEventListener('mouseout',mouseout);d.addEventListener('click',click,true);d.addEventListener('submit',submit,true);d.addEventListener('scroll',scroll,true);d.addEventListener('keydown',keydown,true);d.addEventListener('dragstart',dragstart,true);d.addEventListener('dragover',dragover,true);d.addEventListener('dragleave',dragleave,true);d.addEventListener('drop',drop,true);d.addEventListener('dragend',dragend,true);f.contentWindow?.addEventListener('resize',resize);
      cleanupDocument=()=>{d.removeEventListener('mouseover',mouseover);d.removeEventListener('mouseout',mouseout);d.removeEventListener('click',click,true);d.removeEventListener('submit',submit,true);d.removeEventListener('scroll',scroll,true);d.removeEventListener('keydown',keydown,true);d.removeEventListener('dragstart',dragstart,true);d.removeEventListener('dragover',dragover,true);d.removeEventListener('dragleave',dragleave,true);d.removeEventListener('drop',drop,true);d.removeEventListener('dragend',dragend,true);f.contentWindow?.removeEventListener('resize',resize);style.remove()};
      editorRef.current.refresh();
    };
    f.addEventListener('load',onLoad);return()=>{cleanupDocument();f.removeEventListener('load',onLoad)}
  },[e.html,positionToolbar]);

  const action=(fn:()=>void)=>{fn();setTimeout(positionToolbar)};
  return <main className="min-w-0 flex-1 overflow-auto bg-zinc-900 p-2 pb-16 sm:p-4 sm:pb-4 lg:p-5"><div className="relative mx-auto h-full min-h-[420px] overflow-hidden rounded-md bg-white shadow-2xl transition-[width] duration-200 sm:min-h-[500px] sm:rounded-lg" style={{width:widths[e.device],maxWidth:'100%'}}>{e.html?<><iframe ref={e.iframeRef} srcDoc={e.html} sandbox="allow-same-origin" className="h-full min-h-[calc(100dvh-118px)] w-full border-0 sm:min-h-[calc(100dvh-90px)]" title="HTML canvas"/>{toolbar&&<div data-testid="canvas-block-toolbar" className="absolute z-40 flex h-8 items-center gap-0.5 rounded-md border border-zinc-700 bg-zinc-950/95 px-1 shadow-xl backdrop-blur" style={{left:toolbar.left,top:toolbar.top}}><span className="max-w-20 truncate px-1.5 font-mono text-[10px] text-blue-300">&lt;{toolbar.tag}&gt;</span><button onClick={()=>action(()=>e.move(-1))} title="Canvas move up" className="rounded p-1 text-zinc-400 hover:bg-zinc-800 hover:text-white"><ArrowUp size={13}/></button><button onClick={()=>action(()=>e.move(1))} title="Canvas move down" className="rounded p-1 text-zinc-400 hover:bg-zinc-800 hover:text-white"><ArrowDown size={13}/></button><button onClick={()=>e.copyBlock()} title="Canvas copy block" className="rounded p-1 text-zinc-400 hover:bg-zinc-800 hover:text-white"><ClipboardCopy size={13}/></button><button disabled={!e.hasCopiedBlock} onClick={()=>action(()=>e.pasteBlock('after'))} title="Canvas paste after" className="rounded p-1 text-zinc-400 hover:bg-zinc-800 hover:text-white disabled:opacity-30"><ClipboardPaste size={13}/></button><button onClick={()=>action(()=>e.duplicate())} title="Canvas duplicate" className="rounded p-1 text-zinc-400 hover:bg-zinc-800 hover:text-white"><Copy size={13}/></button><button onClick={()=>{e.remove();setToolbar(null)}} title="Canvas delete" className="rounded p-1 text-red-400 hover:bg-red-500/15 hover:text-red-300"><Trash2 size={13}/></button></div>}</>:<div className="flex h-full min-h-[420px] items-center justify-center px-6 text-center text-sm text-zinc-400 sm:min-h-[500px]">Upload an HTML file to start editing</div>}</div></main>
}
