import{useEffect,useMemo,useState}from'react';
import{ArrowDown,ArrowUp,Copy,Plus,Search,Trash2,X}from'lucide-react';
import{deleteCssRule,duplicateCssRule,insertCssRule,listCssRules,moveCssRule,parseDeclarations,renameCssRule,serializeDeclarations,updateCssRule,type CssDeclaration}from'../editor/cssRules';

export function CssRuleManager({css,onChange,onCommit,defaultSelector='',defaultContext=''}:{css:string;onChange:(css:string)=>void;onCommit:()=>void;defaultSelector?:string;defaultContext?:string}){
  const rules=useMemo(()=>listCssRules(css),[css]);
  const[query,setQuery]=useState('');const[selectedKey,setSelectedKey]=useState('');const[newSelector,setNewSelector]=useState(defaultSelector);const[selector,setSelector]=useState('');const[declarations,setDeclarations]=useState('');const[rows,setRows]=useState<CssDeclaration[]>([]);
  const filtered=rules.filter(r=>`${r.selector} ${r.context}`.toLowerCase().includes(query.trim().toLowerCase()));
  const selected=rules.find(r=>r.path.join('.')===selectedKey)||null;
  useEffect(()=>{setNewSelector(defaultSelector)},[defaultSelector]);
  useEffect(()=>{if(selected){setSelector(selected.selector);setDeclarations(selected.declarations);setRows(parseDeclarations(selected.declarations))}else{setSelector('');setDeclarations('');setRows([]);if(selectedKey)setSelectedKey('')}},[selected?.path.join('.'),selected?.selector,selected?.declarations]);
  const choose=(key:string)=>{onCommit();setSelectedKey(key)};
  const applyDeclarations=(value:string)=>{setDeclarations(value);setRows(parseDeclarations(value));if(selected)onChange(updateCssRule(css,selected.path,value))};
  const changeRow=(index:number,patch:Partial<CssDeclaration>)=>{const next=rows.map((r,i)=>i===index?{...r,...patch}:r);setRows(next);const raw=serializeDeclarations(next);setDeclarations(raw);if(selected)onChange(updateCssRule(css,selected.path,raw))};
  const addRow=()=>{const next=[...rows,{property:'',value:'',priority:''}];setRows(next)};
  const removeRow=(index:number)=>{const next=rows.filter((_,i)=>i!==index);setRows(next);const raw=serializeDeclarations(next);setDeclarations(raw);if(selected)onChange(updateCssRule(css,selected.path,raw));onCommit()};
  const rename=()=>{if(!selected||!selector.trim())return;onChange(renameCssRule(css,selected.path,selector));onCommit()};
  const duplicate=()=>{if(!selected)return;onChange(duplicateCssRule(css,selected.path));onCommit()};
  const remove=()=>{if(!selected)return;onChange(deleteCssRule(css,selected.path));onCommit();setSelectedKey('')};
  const move=(dir:-1|1)=>{if(!selected)return;onChange(moveCssRule(css,selected.path,dir));onCommit();setSelectedKey('')};
  const create=()=>{const value=newSelector.trim();if(!value)return;onChange(insertCssRule(css,value,defaultContext));onCommit();setNewSelector(defaultSelector)};
  return <div className="mb-2 rounded-md border border-zinc-800 bg-zinc-900/40 p-2" aria-label="CSS rule manager">
    <div className="mb-2 flex items-center justify-between"><div className="text-[10px] font-semibold uppercase tracking-wider text-zinc-600">Rule manager</div><span className="text-[9px] text-zinc-600">{rules.length} rules</span></div>
    <div className="mb-2 flex items-center gap-1 rounded border border-zinc-800 bg-zinc-950 px-2"><Search size={11} className="text-zinc-600"/><input aria-label="Search CSS rules" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter selectors..." className="min-w-0 flex-1 bg-transparent py-1.5 text-[10px] text-zinc-300 outline-none"/>{query&&<button onClick={()=>setQuery('')} title="Clear rule search" className="text-zinc-600 hover:text-zinc-300"><X size={11}/></button>}</div>
    <div className="mb-2 flex gap-1"><input aria-label="New CSS selector" value={newSelector} onChange={e=>setNewSelector(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();create()}}} placeholder=".card" className="min-w-0 flex-1 rounded border border-zinc-800 bg-zinc-950 px-2 py-1.5 font-mono text-[10px] text-zinc-300 outline-none focus:border-blue-500"/><button onClick={create} disabled={!newSelector.trim()} className="inline-flex items-center gap-1 rounded bg-zinc-800 px-2 text-[10px] text-zinc-300 hover:bg-zinc-700 disabled:opacity-35"><Plus size={11}/>Add</button></div>
    {!rules.length?<div className="rounded border border-dashed border-zinc-800 p-3 text-center text-[10px] text-zinc-600">No editable style rules yet.</div>:<div className="max-h-36 space-y-1 overflow-auto">{filtered.map(rule=>{const key=rule.path.join('.');return <button key={key} onClick={()=>choose(key)} className={`block w-full rounded px-2 py-1.5 text-left ${selectedKey===key?'bg-blue-500/10':'hover:bg-zinc-800'}`}><code className="block truncate text-[10px] text-blue-300">{rule.selector}</code>{rule.context&&<span className="block truncate text-[9px] text-zinc-600">{rule.context}</span>}</button>})}{rules.length>0&&!filtered.length&&<div className="p-2 text-center text-[10px] text-zinc-600">No matching rules.</div>}</div>}
    {selected&&<div className="mt-2 border-t border-zinc-800 pt-2">
      <div className="mb-1 flex gap-1"><input aria-label="CSS rule selector" value={selector} onChange={e=>setSelector(e.target.value)} onBlur={rename} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();rename()}}} className="min-w-0 flex-1 rounded border border-zinc-800 bg-zinc-950 px-2 py-1 font-mono text-[10px] text-zinc-300 outline-none focus:border-blue-500"/><button onClick={()=>move(-1)} title="Move CSS rule up" className="rounded p-1 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-200"><ArrowUp size={12}/></button><button onClick={()=>move(1)} title="Move CSS rule down" className="rounded p-1 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-200"><ArrowDown size={12}/></button><button onClick={duplicate} title="Duplicate CSS rule" className="rounded p-1 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-200"><Copy size={12}/></button><button onClick={remove} title="Delete CSS rule" className="rounded p-1 text-zinc-500 hover:bg-red-500/10 hover:text-red-300"><Trash2 size={12}/></button></div>
      {selected.context&&<div className="mb-2 truncate text-[9px] text-zinc-600">{selected.context}</div>}
      <div className="space-y-1.5" aria-label="Structured CSS declarations">{rows.map((row,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-1"><input aria-label={`CSS property ${i+1}`} value={row.property} onChange={e=>changeRow(i,{property:e.target.value})} onBlur={onCommit} placeholder="padding" className="min-w-0 rounded border border-zinc-800 bg-zinc-950 px-2 py-1 text-[10px] text-zinc-300 outline-none focus:border-blue-500"/><input aria-label={`CSS value ${i+1}`} value={row.value} onChange={e=>changeRow(i,{value:e.target.value})} onBlur={onCommit} placeholder="20px" className="min-w-0 rounded border border-zinc-800 bg-zinc-950 px-2 py-1 text-[10px] text-zinc-300 outline-none focus:border-blue-500"/><button onClick={()=>removeRow(i)} title={`Remove CSS declaration ${i+1}`} className="rounded px-1 text-zinc-600 hover:bg-red-500/10 hover:text-red-300"><Trash2 size={11}/></button></div>)}</div>
      <button onClick={addRow} className="mt-1.5 inline-flex items-center gap-1 text-[10px] text-zinc-500 hover:text-zinc-300"><Plus size={11}/>Add declaration</button>
      <textarea aria-label="Rule declarations" value={declarations} onChange={e=>applyDeclarations(e.target.value)} onBlur={onCommit} spellCheck={false} placeholder="padding: 20px;" className="mt-2 min-h-16 w-full resize-y rounded-md border border-zinc-800 bg-zinc-950 p-2 font-mono text-[10px] leading-5 text-zinc-400 outline-none focus:border-blue-500"/>
    </div>}
  </div>;
}
